version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  
  php-fpm:
    container_name: php-fpm
    image: framgia/laravel-php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini
  
  mysql:
    container_name: mysql
    image: mysql:8.0.20
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
  
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8081:8080
volumes:
  mysqldata: {}
